# Copyright 2025 Alexander Alten (novatechflow), NovaTechflow (novatechflow.com).
# This project is supported and financed by Scalytics, Inc. (www.scalytics.io).
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- if .Values.console.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kafscale.componentName" (dict "root" . "component" "console") }}
  labels:
{{ include "kafscale.labels" . | indent 4 }}
    app.kubernetes.io/component: console
spec:
  replicas: {{ .Values.console.replicaCount }}
  selector:
    matchLabels:
{{ include "kafscale.componentSelectorLabels" (dict "root" . "component" "console") | indent 6 }}
  template:
    metadata:
      labels:
{{ include "kafscale.componentSelectorLabels" (dict "root" . "component" "console") | indent 8 }}
{{- with .Values.console.podAnnotations }}
      annotations:
{{ toYaml . | indent 8 }}
{{- end }}
    spec:
{{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{- range .Values.imagePullSecrets }}
        - name: {{ . }}
{{- end }}
{{- end }}
      containers:
        - name: console
          image: "{{ .Values.console.image.repository }}:{{ ternary "latest" (default .Chart.AppVersion .Values.console.image.tag) .Values.console.image.useLatest }}"
          imagePullPolicy: {{ ternary "Always" .Values.console.image.pullPolicy .Values.console.image.useLatest }}
          env:
            - name: KAFSCALE_CONSOLE_HTTP_ADDR
              value: ":8080"
{{- if .Values.console.auth.username }}
            - name: KAFSCALE_UI_USERNAME
              value: "{{ .Values.console.auth.username }}"
{{- end }}
{{- if .Values.console.auth.password }}
            - name: KAFSCALE_UI_PASSWORD
              value: "{{ .Values.console.auth.password }}"
{{- end }}
{{- if .Values.console.etcdEndpoints }}
            - name: KAFSCALE_CONSOLE_ETCD_ENDPOINTS
              value: "{{ join "," .Values.console.etcdEndpoints }}"
{{- end }}
{{- if .Values.console.etcd.username }}
            - name: KAFSCALE_CONSOLE_ETCD_USERNAME
              value: "{{ .Values.console.etcd.username }}"
{{- end }}
{{- if .Values.console.etcd.password }}
            - name: KAFSCALE_CONSOLE_ETCD_PASSWORD
              value: "{{ .Values.console.etcd.password }}"
{{- end }}
{{- if .Values.console.metrics.brokerMetricsURL }}
            - name: KAFSCALE_CONSOLE_BROKER_METRICS_URL
              value: "{{ .Values.console.metrics.brokerMetricsURL }}"
{{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
{{- if .Values.console.resources }}
{{ toYaml .Values.console.resources | indent 12 }}
{{- else }}
            {}
{{- end }}
{{- with .Values.console.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.console.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.console.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- end }}
