# Copyright 2025-2026 Alexander Alten (novatechflow), NovaTechflow (novatechflow.com).
# This project is supported and financed by Scalytics, Inc. (www.scalytics.io).
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

imagePullSecrets: []

serviceAccount:
  create: true
  name: ""

rbac:
  create: true

operator:
  replicaCount: 2
  image:
    repository: ghcr.io/novatechflow/kafscale-operator
    tag: ""
    useLatest: false
    pullPolicy: IfNotPresent
  brokerImage:
    repository: ghcr.io/novatechflow/kafscale-broker
    tag: ""
    useLatest: false
  etcdSnapshotEtcdctlImage:
    repository: ghcr.io/novatechflow/kafscale-etcd-tools
    tag: ""
    useLatest: false
  etcdReplicas: 3
  etcdStorageSize: ""
  etcdStorageClass: ""
  etcdStorageMemory: false
  etcdEndpoints:
    - "http://etcd:2379"
  leaderKey: "kafscale-operator"
  podAnnotations: {}
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  metrics:
    enabled: true
    port: 8080
    service:
      annotations: {}
    serviceMonitor:
      enabled: false
      interval: 30s
      scrapeTimeout: 10s
      labels: {}
    prometheusRule:
      enabled: false
      labels: {}

console:
  enabled: true
  replicaCount: 1
  image:
    repository: ghcr.io/novatechflow/kafscale-console
    tag: ""
    useLatest: false
    pullPolicy: IfNotPresent
  auth:
    username: ""
    password: ""
  etcdEndpoints: []
  etcd:
    username: ""
    password: ""
  metrics:
    brokerMetricsURL: ""
  podAnnotations: {}
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: false
    className: ""
    annotations: {}
    hosts:
      - host: console.local
        paths:
          - path: /
            pathType: Prefix
    tls: []

proxy:
  enabled: false
  replicaCount: 2
  image:
    repository: ghcr.io/novatechflow/kafscale-proxy
    tag: ""
    useLatest: false
    pullPolicy: IfNotPresent
  health:
    enabled: true
    port: 9094
  backendCacheTTLSeconds: 60
  advertisedHost: ""
  advertisedPort: 9092
  etcdEndpoints: []
  etcd:
    username: ""
    password: ""
  backends: []
  podAnnotations: {}
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  service:
    type: LoadBalancer
    port: 9092

mcp:
  enabled: false
  namespace:
    name: kafscale-mcp
    create: true
  replicaCount: 1
  image:
    repository: ghcr.io/novatechflow/kafscale-mcp
    tag: ""
    useLatest: false
    pullPolicy: IfNotPresent
  serviceAccount:
    create: true
    name: ""
  auth:
    token: ""
  etcdEndpoints: []
  etcd:
    username: ""
    password: ""
  metrics:
    brokerMetricsURL: ""
  sessionTimeout: ""
  podAnnotations: {}
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: false
    className: ""
    annotations: {}
    hosts:
      - host: mcp.local
        paths:
          - path: /
            pathType: Prefix
    tls: []
